# Generated by Django 5.2.5 on 2025-08-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_icon_class_and_more'),
    ]

    operations = [
    ]
