# Generated by Django 5.2.5 on 2025-08-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0004_alter_inventoryitem_icon_class_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('loading_town', models.CharField(max_length=100)),
                ('loading_postal_code', models.CharField(max_length=10)),
                ('loading_street', models.CharField(max_length=200)),
                ('loading_house_number', models.CharField(max_length=100)),
                ('loading_address', models.CharField(max_length=200)),
                ('unloading_town', models.CharField(max_length=100)),
                ('unloading_postal_code', models.CharField(max_length=10)),
                ('unloading_street', models.CharField(max_length=200)),
                ('unloading_house_number', models.CharField(max_length=100)),
                ('unloading_address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('items', models.ManyToManyField(blank=True, related_name='orders', to='inventory.inventoryitem')),
            ],
        ),
    ]
