# Generated by Django 5.2.5 on 2025-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В очакване'), ('in_progress', 'В процес'), ('completed', 'Завършена'), ('cancelled', 'Отказана')], default='pending', max_length=11),
        ),
    ]
