# Generated by Django 5.2.5 on 2025-08-27 10:32

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
    ]
