# Generated by Django 5.2.5 on 2025-08-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Акаунт', 'verbose_name_plural': 'Акаунти'},
        ),
    ]
