# Generated by Django 5.2.5 on 2025-08-27 21:41

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100)),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=100)),
                ('title_bg', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('subtitle', models.CharField(max_length=100)),
                ('subtitle_bg', models.CharField(max_length=100, null=True)),
                ('subtitle_en', models.CharField(max_length=100, null=True)),
                ('description', markdownx.models.MarkdownxField()),
                ('description_bg', markdownx.models.MarkdownxField(null=True)),
                ('description_en', markdownx.models.MarkdownxField(null=True)),
                ('button_text', models.CharField(max_length=100)),
                ('button_text_bg', models.CharField(max_length=100, null=True)),
                ('button_text_en', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'moving_services',
            },
        ),
    ]
