# Generated by Django 5.2.5 on 2025-08-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_create_moving_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movingservice',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
