# Generated by Django 5.2.5 on 2025-08-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Инвентар Секция',
                'verbose_name_plural': 'Инвентар Секции',
                'db_table': 'inventory_sections',
            },
        ),
    ]
