# Generated by Django 5.2.5 on 2025-08-28 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_create_inventory_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorysection')),
            ],
            options={
                'verbose_name': 'Инвентар Предмет',
                'verbose_name_plural': 'Инвентар Предмети',
                'db_table': 'inventory_items',
            },
        ),
    ]
