# Generated by Django 5.2.5 on 2025-08-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_create_inventory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='icon_class',
            field=models.CharField(help_text='Класа за икона. Можете да намерите икони на: <a href="https://lucide.dev/icons/" target="_blank">Lucide Icons</a>', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorysection',
            name='icon_class',
            field=models.CharField(help_text='Класа за икона. Можете да намерите икони на: <a href="https://lucide.dev/icons/" target="_blank">Lucide Icons</a>', max_length=100),
        ),
    ]
