# Generated by Django 5.2.5 on 2025-09-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_icon_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysection',
            name='title_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventorysection',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
