# Generated by Django 5.2.5 on 2025-09-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorysection_title_bg_inventorysection_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='title_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
