# Generated by Django 5.2.5 on 2025-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=100)),
                ('port', models.PositiveIntegerField()),
                ('tls', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'email_settings',
            },
        ),
    ]
