# Generated by Django 5.2.5 on 2025-08-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_create_email_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'verbose_name': 'Имейл настройки', 'verbose_name_plural': 'Имейл настройки'},
        ),
    ]
