export const ItemErrorCode = {
    ID_INVALID: 'ITEM_ID_INVALID',
    ICON_REQUIRED: 'ITEM_ICON_REQUIRED',
    ICON_TOO_LONG: 'ITEM_ICON_TOO_LONG',
    TITLE_BG_REQUIRED: 'ITEM_TITLE_BG_REQUIRED',
    TITLE_BG_TOO_LONG: 'ITEM_TITLE_BG_TOO_LONG',
    TITLE_EN_REQUIRED: 'ITEM_TITLE_EN_REQUIRED',
    TITLE_EN_TOO_LONG: 'ITEM_TITLE_EN_TOO_LONG',
    SECTION_INVALID: 'ITEM_SECTION_INVALID',
    DATA_INVALID: 'ITEM_DATA_INVALID',
} as const;