export const SectionErrorCode = {
    ID_INVALID: "SECTION_ID_INVALID",
    ICON_REQUIRED: "SECTION_ICON_REQUIRED",
    ICON_TOO_LONG: "SECTION_ICON_TOO_LONG",
    TITLE_BG_REQUIRED: "SECTION_TITLE_BG_REQUIRED",
    TITLE_BG_TOO_LONG: "SECTION_TITLE_BG_TOO_LONG",
    TITLE_EN_REQUIRED: "SECTION_TITLE_EN_REQUIRED",
    TITLE_EN_TOO_LONG: "SECTION_TITLE_EN_TOO_LONG",
    DATA_INVALID: "SECTION_DATA_INVALID",
    NO_ITEMS: "SECTION_NO_ITEMS",
} as const;