export const ServiceErrorCode = {
    ID_INVALID: "SERVICE_ID_INVALID",
    ICON_REQUIRED: "SERVICE_ICON_REQUIRED",
    TITLE_BG_REQUIRED: "SERVICE_TITLE_BG_REQUIRED",
    TITLE_BG_TOO_LONG: "SERVICE_TITLE_BG_TOO_LONG",
    TITLE_EN_REQUIRED: "SERVICE_TITLE_EN_REQUIRED",
    TITLE_EN_TOO_LONG: "SERVICE_TITLE_EN_TOO_LONG",
    SUBTITLE_TOO_LONG: "SERVICE_SUBTITLE_TOO_LONG",
    DESCRIPTION_BG_REQUIRED: "SERVICE_DESCRIPTION_BG_REQUIRED",
    DESCRIPTION_EN_REQUIRED: "SERVICE_DESCRIPTION_EN_REQUIRED",
    PRICE_REQUIRED: "SERVICE_PRICE_REQUIRED",
    DATA_INVALID: "SERVICE_DATA_INVALID",
} as const;